version: '3.9'

services:

  api:
    build: .
    restart: always
    volumes:
    - .:/app
  
  nginx:
    image: nginx:latest
    volumes:
      - ./conf.d:/etc/nginx/conf.d

    depends_on:
      - api
    ports:
      - 3000:3000
